"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-03 19:10:00.000000

The whole schema in one step. Tessera has never had a deployment whose data was worth
carrying forward, so the incremental migrations written while the design settled were folded
into this baseline (design doc Rev 13).

While that remains true, change the schema by editing this file and the models together.
From the first release that real data lives on, stop editing it: add a new migration per
change instead - an existing database remembers its version (`alembic_version`) and can only
be brought forward by new steps, never by a rewritten baseline.

Each `sa.Enum(..., create_constraint=True)` below is also what creates that column's named
CHECK constraint on SQLite; autogenerate emits those constraints a second and third time
as separate `CheckConstraint`s, which are left out.
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from app.db.base import UTCDateTime

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_password_reset_marker",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("consumed_value_hash", sa.String(), nullable=False),
        sa.Column("consumed_at", UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "external_calendar_connections",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "provider", sa.Enum("google", "outlook", "other", name="calendar_provider", create_constraint=True), nullable=False
        ),
        sa.Column("oauth_credentials_ref", sa.String(), nullable=False),
        sa.Column("refresh_interval_minutes", sa.Integer(), nullable=False),
        sa.Column("last_synced_at", UTCDateTime(), nullable=True),
        sa.Column("sync_mode", sa.Enum("read_only", name="sync_mode", create_constraint=True), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "oauth_tokens",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("encrypted_access_token", sa.String(), nullable=False),
        sa.Column("encrypted_refresh_token", sa.String(), nullable=True),
        sa.Column("access_token_expires_at", UTCDateTime(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "schedule_optimizations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "awaiting_approval",
                "applied",
                "nothing_to_do",
                "declined",
                "undone",
                "expired",
                "failed",
                name="schedule_optimization_status",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("requested_at", UTCDateTime(), nullable=False),
        sa.Column("finished_at", UTCDateTime(), nullable=True),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.Column("plan_changed", sa.Boolean(), nullable=False),
        sa.Column("valid_until", UTCDateTime(), nullable=True),
        sa.Column("undo_until", UTCDateTime(), nullable=True),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("plan", sa.JSON(), nullable=True),
        sa.Column("applied_versions", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "schedule_repairs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("done", sa.Integer(), nullable=False),
        sa.Column("moved", sa.Integer(), nullable=False),
        sa.Column("unschedulable", sa.Integer(), nullable=False),
        sa.Column("requested_at", UTCDateTime(), nullable=False),
        sa.Column("finished_at", UTCDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("schedule_repairs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_schedule_repairs_requested_at"), ["requested_at"], unique=False)

    op.create_table(
        "task_templates",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("type", sa.Enum("fixed", "flexible", name="task_template_type", create_constraint=True), nullable=False),
        sa.Column(
            "recurrence_pattern",
            sa.Enum("one_time", "daily", "weekly", "monthly", name="recurrence_pattern", create_constraint=True),
            nullable=False,
        ),
        sa.Column("recurrence_interval", sa.Integer(), nullable=True),
        sa.Column("recurrence_day_of_week", sa.Integer(), nullable=True),
        sa.Column("recurrence_day_of_month", sa.Integer(), nullable=True),
        sa.Column(
            "recurrence_anchor",
            sa.Enum("calendar", "completion", name="recurrence_anchor", create_constraint=True),
            nullable=False,
        ),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("fixed_time_of_day", sa.String(), nullable=True),
        sa.Column("deadline_offset_minutes", sa.Integer(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("estimated_duration_minutes", sa.Integer(), nullable=False),
        sa.Column("reminder_offsets_minutes", sa.JSON(), nullable=False),
        sa.Column("active_hours_override", sa.JSON(), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_settings",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("timezone", sa.String(), nullable=False),
        sa.Column("active_hours", sa.JSON(), nullable=False),
        sa.Column("blackout_dates", sa.JSON(), nullable=False),
        sa.Column("daily_time_budget_minutes", sa.JSON(), nullable=False),
        sa.Column(
            "budget_enforcement", sa.Enum("strict", "soft", name="budget_enforcement", create_constraint=True), nullable=False
        ),
        sa.Column(
            "first_day_of_week",
            sa.Enum(
                "monday",
                "tuesday",
                "wednesday",
                "thursday",
                "friday",
                "saturday",
                "sunday",
                name="first_day_of_week",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("two_factor_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "external_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("connection_id", sa.String(), nullable=False),
        sa.Column("provider_event_id", sa.String(), nullable=False),
        sa.Column("start", UTCDateTime(), nullable=False),
        sa.Column("end", UTCDateTime(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("is_all_day", sa.Boolean(), nullable=False),
        sa.Column("is_transparent", sa.Boolean(), nullable=False),
        sa.Column("fetched_at", UTCDateTime(), nullable=False),
        sa.Column("deleted_at", UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["connection_id"], ["external_calendar_connections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("connection_id", "provider_event_id", name="uq_connection_provider_event"),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("expires_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_instances",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("template_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("type", sa.Enum("fixed", "flexible", name="task_instance_type", create_constraint=True), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("estimated_duration_minutes", sa.Integer(), nullable=False),
        sa.Column("detached", sa.Boolean(), nullable=False),
        sa.Column("scheduled_time", UTCDateTime(), nullable=True),
        sa.Column("deadline", UTCDateTime(), nullable=True),
        sa.Column("nominal_date", UTCDateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "scheduled",
                "in_progress",
                "completed",
                "blocked",
                "missed",
                "dismissed",
                name="task_instance_status",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("status_history", sa.JSON(), nullable=False),
        sa.Column("completed_at", UTCDateTime(), nullable=True),
        sa.Column("generated_at", UTCDateTime(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["task_templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "reminder",
                "creation_conflict",
                "sync_conflict",
                "unschedulable",
                "dependency_at_risk",
                "overdue",
                "budget_exceeded",
                "deadline_missed",
                name="notification_type",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("related_instance_id", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("dismissed_at", UTCDateTime(), nullable=True),
        sa.Column("resolved_at", UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["related_instance_id"], ["task_instances.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_instance_dependencies",
        sa.Column("dependent_id", sa.String(), nullable=False),
        sa.Column("dependency_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["dependency_id"], ["task_instances.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["dependent_id"], ["task_instances.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("dependent_id", "dependency_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_instance_dependencies")
    op.drop_table("notifications")
    op.drop_table("task_instances")
    op.drop_table("sessions")
    op.drop_table("external_events")
    op.drop_table("users")
    op.drop_table("user_settings")
    op.drop_table("task_templates")
    with op.batch_alter_table("schedule_repairs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_schedule_repairs_requested_at"))

    op.drop_table("schedule_repairs")
    op.drop_table("schedule_optimizations")
    op.drop_table("oauth_tokens")
    op.drop_table("external_calendar_connections")
    op.drop_table("admin_password_reset_marker")
    # ### end Alembic commands ###
